- src/app.module.ts
- src/application/application.controller.ts
- src/application/application.module.ts
- src/application/application.service.ts
- src/application/entities/application-project-beneficiary.entity.ts
- src/application/entities/application-project-location.entity.ts
- src/application/entities/application-project.entity.ts
- src/application/entities/application.entity.ts
- src/country/entities/country.entity.ts
- src/province/dto/create-province.dto.ts
- src/province/dto/update-province.dto.ts
- src/province/entities/province.entity.ts
- src/province/province.controller.spec.ts
- src/province/province.controller.ts
- src/province/province.module.ts
- src/province/province.service.spec.ts
- src/province/province.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/90
Added application CRUD
> feat: [sc-90] Application CRUD

- .prettierrc
- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/entities/application-organization-profile.entity.ts
- src/country/country.controller.ts
- src/country/country.service.ts
- src/organization/organization.controller.ts
- src/organization/organization.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/93
> feat: [sc-93] Implement initial Application create endpoints

- src/app.module.ts
- src/application/entities/application.entity.ts
- src/partner/dto/create-partner.dto.ts
- src/partner/dto/update-partner.dto.ts
- src/partner/entities/partner.entity.ts
- src/partner/partner.controller.spec.ts
- src/partner/partner.controller.ts
- src/partner/partner.module.ts
- src/partner/partner.service.spec.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/106
Added partners table
> feat: [sc-106] Partners Table

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/107
> chore: [sc-107] Add Partner Name and Partner ID fetch for Application List

- db/migrations/1708730674339-NewOrganizations.ts
- src/application/entities/application-contact-person.entity.ts
- src/application/entities/application-document.entity.ts
- src/application/entities/application-organization-profile.entity.ts
- src/application/entities/application-proposal-activity.entity.ts
- src/application/entities/application-proposal.entity.ts
- src/application/entities/application.entity.ts
- src/document/entities/document.entity.ts
- src/organization/entities/organization.entity.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/108
> feat: [sc-108] Application API Update

- src/application/entities/application-document.entity.ts
- src/application/entities/application-fiscal-sponsor.entity.ts
- src/application/entities/application-nonprofit-equivalency-determination.entity.ts
- src/application/entities/application-proposal.entity.ts
- src/application/entities/application-references.entity.ts
- src/application/entities/application.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/113
> feat: [sc-113] Application API Update

- src/application/application.service.ts
- src/application/entities/application.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/117
Added all fields of applications table including the auto-generated application number.
> feat: [sc-117] Update generate application

- src/application/application.service.ts
- src/utilities/global.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/118
Added GlobalService
> feat: [sc-118] Extending GlobalService

- src/application/entities/application-project-beneficiary.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/119
Update on the beneficiary
> feat: [sc-119] Application Project Information Update

- src/application/entities/application-nonprofit-equivalency-determination.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/121
Fixed Non-profit Equivalency Determination fields
> feat: [sc-121] Non-profit Equivalency Determination fields

- src/application/application.controller.ts
- src/application/application.service.ts
- src/utilities/global.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/123
Added logs for application delete
> feat: [sc-123] Application Logs

- src/application/application.service.ts
- src/application/entities/application-proposal-activity.entity.ts
- src/province/province.controller.ts
- src/province/province.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/112
> feat: [sc-112] Integrate application initial submission with BE endpoints and save to DB

- src/partner/partner.controller.ts
- src/partner/partner.service.ts
[sc-124]: initial commit
[sc-124]: exposed partner list
> [sc-124]: Application List Delete and Partner List Fetch from DB

- db/migrations/1709366907433-statuses.ts
- db/migrations/1709367372309-substatuses.ts
- src/app.module.ts
- src/application/entities/application-statuses.entity.ts
- src/application/entities/application.entity.ts
- src/partner/partner.controller.ts
- src/partner/partner.service.ts
- src/status/dto/create-status.dto.ts
- src/status/dto/update-status.dto.ts
- src/status/entities/status.entity.ts
- src/status/status.controller.spec.ts
- src/status/status.controller.ts
- src/status/status.module.ts
- src/status/status.service.spec.ts
- src/status/status.service.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/130
Updates:
Statuses table
Application Status
Partners fetch
> feat: [sc-130] Application Status

- src/application/application.controller.ts
- src/application/application.service.ts
- src/partner/partner.controller.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/131
Function Name Update
> feat: [sc-131] Naming Function Update

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/125
> feat: [sc-125] Project Information

- src/application/application.service.ts
- src/application/entities/application-fiscal-sponsor.entity.ts
- src/application/entities/application-project.entity.ts
- src/application/entities/application-proponent-contact.entity.ts
- src/application/entities/application-proponent.entity.ts
- src/application/entities/application-references.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/135
Changed table name of application proponent contacts
> chore: [sc-135] Application Proponent Contacts Update

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/136
Fixed application review data
> feat: [sc-136] Application Review Data

- src/application/application.service.ts
- src/application/entities/application-nonprofit-equivalency-determination.entity.ts
- src/application/entities/application-proposal.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/138
> chore: [sc-138] changed money type to decimal for storing  price types

- .vscode/settings.json
- src/application/application.module.ts
- src/application/application.service.ts
- src/partner/partner.controller.ts
- src/partner/partner.service.ts
- src/status/entities/status.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/139
New Application
> feat: [sc-139] New Application UI and integration to back-end

- db/migrations/1710026538773-countries.ts
- db/migrations/1710027082325-province.ts
- src/application/application.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/140
Added countries and provinces
> feat: [sc-140] BE - Countries and Provinces

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/141
Added auto email for application
> feat: [sc-141] Application Email

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/147
Added ability to set up a new partner
> fix: [sc-147] Generate New Application Fixes

- notes
- src/application/application.service.ts
- src/utilities/global.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/156
Error log
> chore: [sc-156] API temporary error log

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/157
Fixed generation of partner id
> fix: [sc-157] Error in Generating Partner ID

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/158
Additional Delete API for:
application_project_locations
application_proposal_activities
> feat: [sc-158] Additional Delete API for application_project_locationsapplication_proposal_activities

- .gitignore
- src/application/application.service.ts
- src/application/entities/application-proponent.entity.ts
- src/application/entities/application.entity.ts
- src/country/entities/country.entity.ts
- src/organization/entities/organization.entity.ts
- src/partner/entities/partner-contacts.entity.ts
- src/partner/entities/partner-organization.entity.ts
- src/partner/entities/partner.entity.ts
- src/utilities/global.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/159
Application Proponent Update:
application_proponents to partners
application_organization_profile to partner_organizations
application_proponent_contacts to partner_contacts
> chore: [sc-159] Application Proponent Update

- src/application/application.service.ts
- src/partner/entities/partner-organization.entity.ts
- src/partner/entities/partner.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/161
Query update for application review
> chore: [sc-161] Application Review UI update

- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/utilities/get-default-value.utils.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/164
> feat: [sc-164] Application New - Partner Changes

- src/partner/partner.controller.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/165
Partner List Update
> chore: [sc-165] Partners List Update

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/166
> feat: [sc-166] Application New Partner Organization  modifications

- src/app.module.ts
- src/donor/donor.controller.spec.ts
- src/donor/donor.controller.ts
- src/donor/donor.module.ts
- src/donor/donor.service.spec.ts
- src/donor/donor.service.ts
- src/donor/dto/create-donor.dto.ts
- src/donor/dto/update-donor.dto.ts
- src/donor/entities/donor.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/171
Donors Table
> feat: [sc-171] Donors Table

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/174
Added filter on application list
> feat: [sc-174] Application List Filter

- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/utilities/get-default-value.utils.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/162
> chore: [sc-162] Application List Refresh

- src/document/document.controller.ts
- src/document/document.service.ts
- src/document/entities/documentable.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
- src/user/user.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/180
Documentable Save
> feat: [sc-180] Documentable Save

- src/partner/partner.controller.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/177
> feat: [sc-177] Partner List Filters

- db/migrations/1711286454717-types.ts
- src/app.module.ts
- src/application/application.controller.ts
- src/application/application.service.ts
- src/projects/entities/project.entity.ts
- src/review/dto/create-review.dto.ts
- src/review/dto/update-review.dto.ts
- src/review/entities/review.entity.ts
- src/review/entities/reviewable.entity.ts
- src/review/review.controller.spec.ts
- src/review/review.controller.ts
- src/review/review.module.ts
- src/review/review.service.spec.ts
- src/review/review.service.ts
- src/status/status.controller.ts
- src/status/status.service.ts
- src/type/dto/create-type.dto.ts
- src/type/dto/update-type.dto.ts
- src/type/entities/type.entity.ts
- src/type/type.controller.spec.ts
- src/type/type.controller.ts
- src/type/type.module.ts
- src/type/type.service.spec.ts
- src/type/type.service.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/182
> feat: [sc-182] Grants Type and Review

- src/application/application.service.ts
- src/review/entities/reviewable.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/184
Fixed Reviewable
> fix: [sc-184] Reviewable Error

- src/application/entities/application.entity.ts
- src/type/entities/type.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/186
> chore: [sc-186] Associate Type in Applications (type_application_relation)

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/189
Fixed error while merging
> fix: [sc-189] Application Types Merge Error

- src/application/application.controller.ts
- src/application/application.service.ts
- src/document/document.controller.ts
- src/utilities/upload.utils.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/190
Application review update
> feat: [sc-190] Application Review Updates

- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/entities/application-recommendation.entity.ts
- src/application/entities/application.entity.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/191
Review Delete
Save Recommendation
> feat: [sc-191] Application Review Updates

- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/utilities/get-default-value.utils.ts
- src/application/utilities/get-parsed-pk.utils.ts
- src/utilities/global.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/154
> feat: [sc-154] Implement autosave in Application New Component

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/194
Application Review Download Comments
> feat: [sc-194] Application Review Download Comments

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/199
> chore: [sc-199] fix project information and proposed activity new

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/200
Fixed Application Service Find Issue
> fix: [sc-200] Application Service Find Issue

- src/application/application.controller.ts
- src/application/application.service.ts
- src/partner/entities/partner-organization-references.entity.ts
- src/review/entities/review.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/230
Review display update
Mark as resolved function
> feat: [sc-230] Application Review Update

- src/document/document.controller.ts
- src/document/document.service.ts
- src/utilities/upload.utils.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/231
Fixed upload and attachment link
> feat: [sc-231] Attachments inside New Application and Application Review

- src/application/application.service.ts
- src/user/user.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/201
> fix: [sc-201] Application New - Project Information Error

- src/application/application.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/235
Removed authguard for application requests
> fix: [sc-235] New Application error on saving

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/239
Added attachment delete function
> feat: [sc-239] Application Review Attachments

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/243
Application Success Email
> feat: [sc-243] Application Success Email

- src/partner/entities/partner-contacts.entity.ts
- src/partner/entities/partner-fiscal-sponsor.entity.ts
- src/partner/entities/partner-organization-bank.entity.ts
- src/partner/entities/partner-organization-other-information.entity.ts
- src/partner/entities/partner-organization.entity.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/245
Additional tables for partners
> feat: [sc-245] Partner Organization

- src/application/application.service.ts
- src/application/entities/application.entity.ts
- src/document/document.controller.ts
- src/document/document.service.ts
- src/partner/entities/partner.entity.ts
- src/partner/partner.controller.ts
- src/projects/entities/project.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/210
New Application Delete attachments
> feat: [sc-210] Application New - action buttons for attachments

- src/partner/partner.controller.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/246
> feat: [sc-246] Partner View - Initial Implementation Modification of Fields

- src/application/application.service.ts
- src/document/entities/document.entity.ts
- src/partner/entities/partner.entity.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/255
Partner Information Attachments
> feat: [sc-255] Partner Information Attachments

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/262
Removed where reviews for now
> fix: [sc-262] Application Review Fetch Error

- src/application/application.service.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/263
Fixed missing partner documents
> fix: [sc-263] Partner Documents Issue

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/261
> feat: [sc-261] Application New - cannot save contact person of references

- src/application/application.service.ts
- src/application/entities/application.entity.ts
- src/partner/entities/partner-nonprofit-equivalency-determination.entity.ts
- src/partner/entities/partner.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/244
application non profit equivalency to partner
> chore: [sc-244] Non profit equivalency table migration

- src/application/application.service.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/232
> feat: [sc-232] Application New - disable next text box field if chosen NO option

- src/application/application.service.ts
- src/document/document.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/264
Application and Partner Attachments
> feat: [sc-264] Application and Partner Attachments

- src/partner/entities/partner-assessment.entity.ts
- src/partner/entities/partner.entity.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/266
Partner Assessments
> feat: [sc-266] Partner Assessments

- db/migrations/1712315815238-donors.ts
- src/donor/donor.service.ts
- src/donor/entities/donor.entity.ts
- src/type/entities/type.entity.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/267
Donors Migration Data
fetch donors in application list
> chore: [sc-267] Donors Migration

- src/application/application.service.ts
- src/partner/partner.controller.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/269
> feat: [sc-269] Partners - Add New Partner

- src/application/application.controller.ts
- src/application/application.service.ts
- src/partner/entities/partner-assessment.entity.ts
- src/partner/partner.controller.ts
- src/partner/partner.service.ts
- src/utilities/global.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/268
> chore: [sc-268] Partner View - Assessment and Project

- src/application/application.service.ts
- src/application/entities/application-statuses.entity.ts
- src/application/entities/application.entity.ts
- src/partner/partner.controller.ts
- src/partner/partner.service.ts
- src/review/entities/review.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/220
Application Review Update
> feat: [sc-220] Application Review - flow of comments section

- src/application/application.service.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/272
> feat: [sc-272] Application New - Fix Save Partner and Contact Info reference and Partner View - Fix fetching specific partner

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/273
Fixed issues on application statuses
> fix: [sc-273] Application Status Update

- src/donor/donor.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/283
Donors CRUD Update
> feat: [sc-283] Donors CRUD

- src/application/application.service.ts
- src/document/document.service.ts
- src/document/entities/document.entity.ts
- src/partner/entities/partner-fiscal-sponsor.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/294
Budget Review and Finalization
Organization Bank Account Information
Fiscal Sponsor Bank Details
> feat: [sc-294] Budget Review and Finalization

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/298
> feat: [sc-298] Partner Review - Other Information

- src/application/application.service.ts
- src/document/document.service.ts
- src/document/entities/document.entity.ts
- src/partner/entities/partner-organization-other-information.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/300
Partner Other Information
> feat: [sc-300] Partner Other Information

- src/application/application.service.ts
- src/document/document.service.ts
- src/document/entities/document.entity.ts
- src/partner/entities/partner-nonprofit-equivalency-determination.entity.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/279
Non profit documents
> feat: [sc-279] Partner - non profit equivalency determination

- src/partner/entities/partner.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/282
Set partner name as unique
> feat: [sc-282] Partner - search

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/226
Generate link update
> fix: [sc-226] Settings Links - does not show proper information

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/224
Application Flow update
> feat: [sc-224] Application Review - flow of an application in the review stages

- src/application/application.service.ts
- src/partner/entities/partner-organization-other-information-financial-hr.entity.ts
- src/partner/entities/partner-organization-other-information.entity.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/321
Financial Human Resources
> feat: [sc-321] Other Information - Financial Humar Resources

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/270
Fixed slow query
> chore: [sc-270] SQL Performance Issue on application .find()

- src/application/application.controller.ts
- src/application/application.module.ts
- src/application/application.service.ts
- src/application/utilities/lib/application-helpers.module.ts
- src/application/utilities/lib/application-query-helpers/application-query-helpers.service.spec.ts
- src/application/utilities/lib/application-query-helpers/application-query-helpers.service.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/335
> fix: [sc-335] Application New - Fix missing partner

- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/entities/application-statuses.entity.ts
- src/application/entities/application.entity.ts
- src/partner/entities/partner-organization-other-information-financial-human-resources.entity.ts
- src/partner/entities/partner-organization-other-information.entity.ts
- src/partner/partner.controller.ts
- src/partner/partner.service.ts
- src/projects/entities/project-statuses.entity.ts
- src/projects/entities/project.entity.ts
- src/type/entities/type.entity.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/336
Query update for application findAll
> chore: [sc-336] Application List Query Update

- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/utilities/lib/application-query-helpers/application-query-helpers.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/337
Query Update
> chore: [sc-337] Query Update for Generated and Review

- src/application/application.controller.ts
- src/application/utilities/lib/application-query-helpers/application-query-helpers.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/340
> feat: [sc-340] Grants Review - Project Information

- src/application/application.controller.ts
- src/application/application.service.ts
- src/projects/entities/project.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.module.ts
- src/projects/projects.service.ts
- src/review/entities/review.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/365
Grants Module Query Update
> chore: [sc-365] Grants Query Update

- src/document/entities/document.entity.ts
- src/projects/entities/project-funding-liquidation.entity.ts
- src/projects/entities/project-funding-report.entity.ts
- src/projects/entities/project-funding.entity.ts
- src/projects/entities/project.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/346
Project Funding
> feat: [sc-346] Grants Review - Funding Release

- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/366
Fixed partner display issue
> fix: [sc-366] Partner Review display issue

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/324
Application Status
> feat: [sc-324] Application Status

- src/projects/entities/project-site.entity.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/327
Project Site Table
> feat: [sc-327] Grants Review - Project Information

- src/document/entities/document.entity.ts
- src/projects/entities/project.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/362
Project Information Attachments
> feat: [sc-362] Grants Review - Project Information Attachments

- src/application/application.service.ts
- src/projects/projects.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/368
> chore: [sc-368] Grant Review - Fix fetching and saving project information and activities & timeline

- src/application/application.service.ts
- src/projects/entities/project-recommendation.entity.ts
- src/projects/entities/project.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/344
Grant Review - Reviews
> feat: [sc-344] Grants Review - Reviews

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/326
Grants List - Changing of Status
> feat: [sc-326] Grants List - Changing of status

- src/projects/projects.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/369
Fixed error when no partner pk
> fix: [sc-369] Grants List Error

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/370
Fixed flow of status from application to grant
> fix: [sc-370] Status Flow from Application to Grant

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/371
Sending email was disabled
> fix: [sc-371] New Link Email

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/372
Fixed success email not saving
> fix: [sc-372] Success Email Not saving

- src/role/entities/role.entity.ts
- src/role/role.controller.ts
- src/role/role.service.ts
- src/utilities/global.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/375
Roles Update
> chore: [sc-375] Roles Updates

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/376
Funding Attachments
> feat: [sc-376] Funding Attachments

- src/document/document.controller.ts
- src/document/document.service.ts
- src/projects/entities/project-funding.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/377
Funding Liquidation Attachments
> feat: [sc-377] Liquidation Attachments

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/378
> chore: [sc-378] Grants Review - Fix saving project funding

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/379
Fixed File Uploader Status
Fixed deletion of bank receipt in project funding
> fix: [sc-379] Fixed minor Issues

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/381
> chore: [sc-381] Grant Review - Project Information add Project Site

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
- src/user/entities/user-role.entity.ts
- src/user/entities/user.entity.ts
- src/user/user.controller.ts
- src/user/user.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/382
User Roles
Financial Management Training
> feat: [sc-382] User Roles

- src/projects/entities/project-funding-report.entity.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/385
> chore: [sc-385] Grant Review - Funding Release Fixed attach documents

- src/projects/entities/project-event-attendees.entity.ts
- src/projects/entities/project-event.entity.ts
- src/projects/entities/project.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/352
Project Attendees
> feat: [sc-352] Grants Review - Attendees

- src/projects/entities/project-objective-result.entity.ts
- src/projects/entities/project-output.entity.ts
- src/projects/entities/project.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/354
Project Output
> feat: [sc-354] Grants Review - Outputs

- src/application/application.service.ts
- src/projects/entities/project-beneficiary.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/350
> feat: [sc-350] Grants Review - Beneficiaries

- src/projects/entities/project-capdev-observe.entity.ts
- src/projects/entities/project-capdev-skill.entity.ts
- src/projects/entities/project-capdev.entity.ts
- src/projects/entities/project.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/356
> feat: [sc-356] Grants Review - CapDev

- src/projects/entities/project-lesson.entity.ts
- src/projects/entities/project.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/360
> feat: [sc-360] Grants Review - Lessons

- src/app.controller.ts
- src/document/document.service.ts
- src/projects/entities/project-link.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
- src/user/entities/user.entity.ts
- src/user/user.controller.ts
- src/utilities/upload.utils.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/358
Documentation
> feat: [sc-358] Grants Review - Documentation

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/394
> fix: [sc-394] Settings - Links does not reflect on the list after clicking generate and then send

- src/role/role.service.ts
- src/user/user.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/399
Permissions
> feat: [sc-399] Application Review User Permissions

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/421
> fix: [sc-421] Document Fetch hang upon fetch and modify filters for Application list

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/403
> feat: [sc-403] Dashboard - Total per Grant Function

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/406
> feat: [sc-406] Dashboard - Total Grants for Year/Country

- src/app.module.ts
- src/template/dto/create-template.dto.ts
- src/template/dto/update-template.dto.ts
- src/template/entities/template.entity.ts
- src/template/template.controller.spec.ts
- src/template/template.controller.ts
- src/template/template.module.ts
- src/template/template.service.spec.ts
- src/template/template.service.ts
- src/user/entities/user.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/423
Email Templates
> feat: [sc-423] Email Templates

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/442
Fixed issue in saving application
> fix: [sc-442] New Application Saving issue

- src/application/application.controller.ts
- src/application/application.module.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/478
Added grant statuses to application status
> feat: [sc-478] Application Status - Grants Statuses

- src/application/application.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/435
> feat: [sc-435] Partner's Information attachment

- src/partner/partner.controller.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/455
> feat: [sc-455] Partner's Information - Assessment

- src/account/account.module.ts
- src/application/application.controller.ts
- src/application/application.module.ts
- src/application/application.service.ts
- src/application/utilities/lib/application-helpers.module.ts
- src/auth/auth.service.ts
- src/template/template.service.ts
- src/user/user.module.ts
- src/user/user.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/504
Use email templates when sending emails
> feat: [sc-504] Use Email Templates when sending emails

- src/projects/projects.service.ts
- src/user/user.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/457
Fixed error in saving users.
> fix: [sc-457] Settings - Users

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/471
Grants Attendees Update
> feat: [sc-471] Grants Progress - Attendees

- src/donor/donor.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/463
Donor list update inside Grants > Choose which donor
> feat: [sc-463] Grants - Donor Section

- src/application/application.controller.ts
- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/447
> feat: [sc-447] Application Review - Budget Review and Finalization

- src/role/role.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/458
> feat: [sc-458] Grants Progress - Top Information

- src/role/role.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/456
Fixed roles
> feat: [sc-456] Settings - Roles

- src/donor/entities/donor.entity.ts
- src/projects/entities/project-funding.entity.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/451
Added donor to tranche
> feat: [sc-451] Grants - List (Donor Section)

- src/application/application.service.ts
- src/projects/entities/project-funding-liquidation.entity.ts
- src/projects/entities/project-funding.entity.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/466
Added multiple liquidations for fund release
> feat: [sc-466] Grants Progress - Fund Release

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/408
Total per donor
> feat: [sc-408] Dashboard - Total per Donor

- src/projects/entities/project.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/416
Grant Progress and Closing
> feat: [sc-416] Dashboard - Grant Progress and Closing

- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/entities/application.entity.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/414
> feat: [sc-414] Dashboard - Application

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/418
> feat: [sc-418] Dashboard - Overdue Tenches/Reports

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/419
> feat: [sc-419] Dashboard - Aging Projects and Tranches

- src/document/document.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/214
Fixed attachment component
> feat: [sc-214] Application New - separate attachment for each form section

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/418
> feat: [sc-418] Dashboard - Overdue Tranches/Reports

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/720
Reports Summary of Beneficiaries
> feat: [sc-720] Reports > Summary of Beneficiaries

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/412
> feat: [sc-412] Dashboard - Grant Status

- src/application/application.controller.ts
- src/application/application.service.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/722
Reports > Application
> feat: [sc-722] Reports > Applications

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/740
Fixed grant filter by donor
> feat: [sc-740] Grant Filter - Choose which donor

- src/application/application.service.ts
- src/cron/mailer/mailer.service.ts
- src/email/email.controller.ts
- src/projects/projects.service.ts
- src/user/user.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/601
Added test email
> feat: [sc-601] Email Templates

- src/projects/entities/project-event-attendees.entity.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/770
Data Collection
> feat: [sc-770] Data Collection

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/752
> feat: [sc-752] Grant - Fund Release

- src/cron/mailer/mailer.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/842
Added email count to email cron
> feat: [sc-842] Email Cron Email Count

- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/724
> feat: [sc-724] Reports > Location

- src/partner/partner.controller.ts
- src/partner/partner.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/882
> feat: [sc-882] Partners List Sorting

- src/application/application.controller.ts
- src/application/application.service.ts
- src/application/entities/application.entity.ts
- src/log/entities/log.entity.ts
- src/utilities/global.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/879
Changed how the application number is generated
> feat: [sc-879] Generation of Application Code

- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/955
> feat: [sc-955] Dashboard - Grant Function

- src/projects/entities/project-code.entity.ts
- src/projects/entities/project-funding.entity.ts
- src/projects/projects.controller.ts
- src/projects/projects.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/880
> feat: [sc-880] Generation of Grant Code

- src/partner/partner.controller.ts
- src/projects/projects.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/1096
Fixed random errors
> fix: [sc-1096] Random Errors

- src/application/application.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/1098
> fix: [sc-1098] Error in fetching applicantions

- src/document/document.controller.ts
- src/document/document.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/1099
File upload handler update
> fix: [sc-1099] File Upload Handler Update

- src/partner/partner.controller.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/1100
Added check if document exists
> fix: [sc-1100] Partner Page Error

- src/application/application.service.ts
Story details: https://app.shortcut.com/straw-hat-pirates/story/1101
Fixed error
> fix: [sc-1101] Partner Error
